version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    volumes:
      - /home/jesse/WatchNext
    ports:
      - "3000:3000"
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    expose:
      - "3000"