version: '3'
services:
  # service configuration for our dockerized Rails app
  app:
    # use the Dockerfile next to this file
    build: .


   
    # sources environment variable configuration for our app
    env_file: .env
   
    # rely on the RAILS_ENV value of the host machine
    environment:
      RAILS_ENV: $RAILS_ENV

   
    # makes the app container aware of the DB container
    links:
      - db
   
    # expose the port we configured Unicorn to bind to
    expose:
      - "3000"

  # service configuration for our database
  db:
   
    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:latest
   
    # persist the database between containers by storing it in a volume
    # volumes:
    #   - /Users/jessecalton/WatchNext/lib/postgresql/data

  # service configuration for our web server
  web:
   
    # set the build context to the root of the Rails app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

    volumes:
      - /Users/jessecalton/WatchNext/
   
    # build with a different Dockerfile
    # dockerfile: /Users/jessecalton/WatchNext/config/containers/Dockerfile-nginx
    
    # makes the web container aware of the app container
    links:
      - app
    
    # expose the port we configured Nginx to bind to
    ports:
      - "3000:3000"
    depends_on:
      - db
