# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20223cb386be2eaeb2e175d8cdf453465dfb486d8e875afd5c39487c42397496754231f3f71d25890d30bd853c1c429b68c3ec466b40dbbadb5e576d14317ae0

test:
  secret_key_base: 4110e9eb94a1358284f4bde58fdf4f04cbd587589536576d9d181cf107b16b7183e4a72b78671a643ad4d93c309f73b284b2354241d6980ceb4eaf7d26d86cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
